<?php

/**
 * @file
 * Creates Islandora Collections from CSV.
 */

// Permissions.
define('ISLANDORA_COLLECTION_CSV_IMPORT_ISLANDORA_COLLECTION_IMPORT_CSV', 'Import collections from csv');

/**
 * Implements hook_menu().
 */
function islandora_collection_csv_import_menu() {
  return array(
    'import_collection_csv' => array(
      'title' => 'Import Collections from CSV',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_collection_import_form'),
      'file' => 'includes/islandora_collection_csv_import.form.inc',
      'access arguments' => array(ISLANDORA_COLLECTION_CSV_IMPORT_ISLANDORA_COLLECTION_IMPORT_CSV),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_collection_csv_import_permission() {
  return array(
    ISLANDORA_COLLECTION_CSV_IMPORT_ISLANDORA_COLLECTION_IMPORT_CSV => array(
      'title' => t('Import Islandora Collections from CSV'),
      'description' => t('Import collections from user-supplied CSV.'),
    ),
  );
}
